# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://TikuisChan.github.io/np_nn/"

git_url = "https://github.com/TikuisChan/np_nn/tree/master/"

def custom_doc_links(name): return None
